### ISSUE TITLE
Publish on AUR

### ISSUE THREAD

**Issue by LethalManBoob** [FanderWasTaken/wine-dependency-hell-solver#1]
Thank :)

**Comment by FanderWasTaken** [comment]
You're welcome. I'm not on Arch so I don't know how to do that to be honest. Maybe someone with more knowledge in that area could help out, cause it will take long time before I do it 😅

**Comment by FanderWasTaken** [comment]
Having time to think about it... I really don't see how anyone would benefit from these scripts being in the AUR. It's run once on your host and then run inside Wine.
