### ISSUE TITLE
Question Regarding Download URL in WDHS.sh Script

### ISSUE THREAD

**Issue by milamer** [FanderWasTaken/wine-dependency-hell-solver#5]
Hi,

I've been reviewing the `WDHS.sh` script and noticed that it downloads a file from the following URL:

```
https://www.ddsystem.com.br/update/setup/vb6+sp6/VS6SP6.EXE
```

This URL seems a bit suspicious to me. Could you please provide more context or rationale behind choosing this source? Specifically, I am concerned about the security and legitimacy of this file. 

Are there any checks or verifications done to ensure the integrity and safety of this download? 

Thank you!

Chris

**Comment by FanderWasTaken** [comment]
Hi! I took the download link from [winetricks](https://github.com/Winetricks/winetricks/blob/master/src/winetricks)

**Comment by FanderWasTaken** [comment]
[Here's what Virus Total has to say](https://www.virustotal.com/gui/file/7fa1d1778824b55a5fceb02f45c399b5d4e4dce7403661e67e587b5f455edbf3/detection)

**Comment by milamer** [comment]
Hey @FanderWasTaken 
Thanks for the quick response. I opened a ticket over at winetricks!

**Comment by FanderWasTaken** [comment]
[Changed the link](https://github.com/FanderWasTaken/wine-dependency-hell-solver/commit/cb62256e5cfcb80fb9ff82240994db4e2a2c10a9)
